spring.application.name=GatewayService
server.port=9094

management.endpoints.web.exposure.include=*
spring.cloud.gateway.server.webflux.routes[0].id=AUTHSERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHSERVICE
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9091
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/app1/**

spring.cloud.gateway.server.webflux.routes[1].id=USERMGMTSERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USERMGMTSERVICE
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/app2/**

spring.cloud.gateway.server.webflux.routes[2].id=APPOINTMENTSERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://APPOINTMENTSERVICE
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/app3/**

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}